### ISSUE TITLE
Basic workflow TODO

### ISSUE THREAD

**Issue by joewandy** [glasgowcompbio/pySubstructures#2]
Some TODO from https://github.com/glasgowcompbio/pySubstructures/blob/master/notebooks/beer_demo.ipynb. All these are necessary before we can swap the GNPS version with this package.

- [ ]  Store motifdb locally as JSON files rather than requesting them from the server each time.
- [ ]  See section 4 in the notebook, clean up code duplications
- [ ] Allow users to provide their own MS1 peaklist
